### ISSUE TITLE
チェックポイントを指定した時に適切に適切にディレクトリが生成されない

### ISSUE THREAD

**Issue by khirotaka** [khirotaka/enchanter#5]
```sh
[A
Traceback (most recent call last):
  File "resnet_from_kaggle.py", line 56, in <module>

pin_memory=torch.cuda.is_available()
  File "/home/XXXXXXXXXX/.local/lib/python3.7/site-packages/enchanter/engine/runner.py", line 151, in train

self.save(checkpoint, epoch=epoch+1)
  File "/home/XXXXXXXXXX/.local/lib/python3.7/site-packages/enchanter/engine/runner.py", line 255, in save

os.mkdir(directory)
FileNotFoundError
: [Errno 2] No such file or directory: './checkpoints/bengali_resnet/'
```

**Comment by khirotaka** [comment]
これは、 `os.mkdir(directory)` を使っているのが問題
